accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/', views.signup, name='signup'),
    url(r'^login/', views.login_view, name='login'),
    url(r'^logout/', views.logout_view, name='logout'),
]

products/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'products'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    path('category1', views.category1, name='cat1'),
    path('category2', views.category2, name='cat2'),
    url(r'^(?P<pk>[0-9]+)/cart/$', views.cart, name='cart'),
    url(r'^(?P<pk>[0-9]+)/cart/(?P<pid>[0-9]+)/$', views.add2cart, name='add2cart'),
    url(r'^(?P<pk>[0-9]+)/cart/remove/(?P<pid>[0-9]+)/$', views.removeFromCart, name='removeFromCart'),
]

shopbox/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url

# to load images
from django.conf.urls.static import static
from django.conf import settings

# for social login
from django.contrib.auth import views as auth_views

import products.views as product_views

urlpatterns = [
    path('products/', include('products.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('checkout/',product_views.checkout, name='checkout'),
    path('', product_views.index, name='index'),
    path('', include('payments.urls')),

    url(r'^login/$', auth_views.LoginView, name='login'),
    url(r'^logout/$', auth_views.LogoutView, name='logout'),
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # <
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>Boxes & Beyond</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <script src="https://kit.fontawesome.com/26ef8f5d5d.js" crossorigin="anonymous"></script>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Boxes & Beyond</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="/products">Products</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="/products/category1">Price <= 200</a>
          <a class="dropdown-item" href="/products/category2">200 < Price <= 400</a>
        </div>
      </li>
      <ul class="navbar-nav">
        {% if user.is_authenticated %}
          <li><a class="nav-link" href="/products/{{ user.id }}/cart" onClick="document.getElementById('cart{{ user.id }}').submit()">Cart</a></li>
          <form id="cart{{ user.id }}" method="POST" action="{% url 'products:cart' pk=user.id %}">
            {% csrf_token %}
            <input type="hidden">
          </form>
          <li><a class="nav-link" href="#" onClick="document.getElementById('logout').submit()">LogOut</a></li>
          <form id="logout" method="POST" action="{% url 'accounts:logout' %}">
            {% csrf_token %}
            <input type="hidden">
          </form>

        {% else %}
          <li><a class="nav-link" href="{% url 'accounts:login' %}">Login</a></li>
          <li><a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a></li>
        {% endif %}
      </ul>
    </ul>
  </div>
</nav>

<br>

<div class="container">
	{% block content %}
	{% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>