products/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'products'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    path('category1', views.category1, name='cat1'),
    path('category2', views.category2, name='cat2'),
    url(r'^(?P<pk>[0-9]+)/cart/$', views.cart, name='cart'),
    url(r'^(?P<pk>[0-9]+)/cart/(?P<pid>[0-9]+)/$', views.add2cart, name='add2cart'),
    url(r'^(?P<pk>[0-9]+)/cart/remove/(?P<pid>[0-9]+)/$', views.removeFromCart, name='removeFromCart'),
]

shopbox/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url

# to load images
from django.conf.urls.static import static
from django.conf import settings

# for social login
from django.contrib.auth import views as auth_views

import products.views as product_views

urlpatterns = [
    path('products/', include('products.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('checkout/',product_views.checkout, name='checkout'),
    path('', product_views.index, name='index'),
    path('', include('payments.urls')),

    url(r'^login/$', auth_views.LoginView, name='login'),
    url(r'^logout/$', auth_views.LogoutView, name='logout'),
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # <
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.timezone import now

class Product(models.Model):
	name = models.CharField(max_length=100)
	photo = models.ImageField(upload_to='./products/static/pictures/')
	cost = models.IntegerField()

	def __str__(self):
		return self.name

class ActiveCart(models.Model):
	order_id = models.AutoField(primary_key=True)
	item = models.ForeignKey(Product, on_delete=models.CASCADE)
	buyer = models.ForeignKey(User, on_delete=models.CASCADE)
	order_date = models.DateTimeField(default=now)
	quantity = models.IntegerField(default=0)

	def __str__(self):
		return self.item.name;

products/views.py
from django.shortcuts import render, redirect
from .models import Product, ActiveCart
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

def index(request):
	# for shopbox homepage
    return render(request, 'products/index.html')

def home(request):
	products = Product.objects.order_by('cost')
	return render(request, 'products/home.html', {'all_products':products})

@login_required
def cart(request, pk):
	cart_items = ActiveCart.objects.filter(buyer__id=pk)
	total_cost = 0
	for obj in cart_items:
		total_cost += (obj.item.cost * obj.quantity)
	return render(request, 'products/cart.html', {'all_items':cart_items, 'total_cost':total_cost})

def category1(request):
	# cost is less than or equal to 200
	cat1_products = Product.objects.filter(cost__lte=200).order_by('cost')
	return render(request, 'products/home.html', {'all_products':cat1_products})

def category2(request):
	# cost is greater than 200 and less than equal to 400
	q1 = Product.objects.filter(cost__gt=200)
	q2 = Product.objects.filter(cost__lte=400)
	cat2_products = q1.intersection(q2).order_by('cost')
	return render(request, 'products/home.html', {'all_products':cat2_products})

@login_required
def add2cart(request, pk, pid):
	product = Product.objects.get(pk=pid)
	buyer = User.objects.get(pk=pk)
	try:
		cart_item = ActiveCart.objects.get(item=product, buyer=buyer)
		cart_item.quantity += 1
	except ObjectDoesNotExist:
		cart_item = ActiveCart.objects.create(item=product, buyer=buyer, quantity=1)
	cart_item.save()
	return redirect('products:cart', pk=pk)

@login_required
def removeFromCart(request, pk, pid):
	product = Product.objects.get(pk=pid)
	cart_item = ActiveCart.objects.get(item=product, buyer=User.objects.get(pk=pk))
	cart_item.quantity -= 1
	cart_item.save()
	if(cart_item.quantity == 0):
		ActiveCart.objects.filter(item=product, buyer=User.objects.get(pk=pk)).delete()
	return redirect('products:cart', pk=pk)

@login_required
def checkout(request):
	return render(request, 'products/checkout.html')

products/templates/products/cart.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">

<h2>Your Cart</h2><br>

{% if all_items.count == 0 %}
	<h4>Your cart looks empty, Let's buy something</h4>
	<h4>Go to Products Page</h4>

{% else %}
	{% for product in all_items.all %}

	<table>
		<tr><h5>{{ product.item.name }}</h5></tr>
		<tr><i class="fas fa-rupee-sign"></i>{{ product.item.cost }}</tr><br>
		<tr><a href="/products/{{ user.id }}/cart/{{ product.item.id }}" onClick="document.getElementById('add{{ user.id }}_{{ product.item.id }}').submit()"><i class="fas fa-caret-up"></i></a>
		<tr><h4>{{ product.quantity }}</h4></tr>
		<tr><a href="/products/{{ user.id }}/cart/remove/{{ product.item.id }}" onClick="document.getElementById('remove{{ user.id }}_{{ product.item.id }}').submit()"><i class="fas fa-caret-down"></i></a></tr>
	</table>

	<br>

	<form id="add{{ user.id }}_{{ product.item.id }}" method="POST" action="{% url 'products:add2cart' pk=user.id pid=product.item.id %}">
		{% csrf_token %}
		<input type="hidden">
	</form>

	<form id="remove{{ user.id }}_{{ product.item.id }}" method="POST" action="{% url 'products:removeFromCart' pk=user.id pid=product.item.id %}">
		{% csrf_token %}
		<input type="hidden">
	</form>

	{% endfor %}

	<h4>Total Cost is {{ total_cost }}</h4>
	<h4><a href="/checkout">Checkout</a></h4>
{% endif %}

{% endblock %}

products/templates/products/checkout.html
{% extends 'base.html' %}

{% block content %}

<h2>Checkout Page</h2>

<h4>Choose your payment mode</h4>

<a href="/pay"><button>Place your order</button></a>

{% endblock %}

products/templates/products/home.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">

<h1>Products</h1>

{% for product in all_products.all %}

<table>
	<tr><h2>{{ product.name }}</h2></tr>
	<tr><img src="{{ product.photo.url }}"></tr><br>
	<tr><h4>{{ product.cost }}</h4></tr>
	{% if user.is_authenticated %}
		<tr><a href="/products/{{ user.id }}/cart/{{ product.id }}" onClick="document.getElementById('add{{ user.id }}_{{ product.id }}').submit()"><button>Add to Cart</button></a></tr>
		
		<form id="add{{ user.id }}_{{ product.id }}" method="POST" action="{% url 'products:add2cart' pk=user.id pid=product.id %}">
			{% csrf_token %}
			<input type="hidden">
		</form>
	{% endif %}
</table>

<br><br>

{% endfor %}

{% endblock %}

products/templates/products/index.html
{% extends 'base.html' %}

{% block content %}

<h1>Boxes & Beyond</h1>

<h2>Your one stop destination for all things fancy</h2>

{% if user.is_authenticated %}
	<h3>You are signed in as {{ request.user.username }}</h3>
{% endif %}

{% endblock %}